version: '3.8'

services:
  frontend:
    build:
      context: ./racing-league-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./racing-league-app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production

networks:
  default:
    driver: bridge